package com.example.shared.data

import kotlinx.serialization.Serializable

@Serializable
data class GridPathCords(val x: Int, val y: Int)

val redBase: List<GridPathCords> = listOf(
    GridPathCords(14, 2),
    GridPathCords(14, 3),
    GridPathCords(16, 2),
    GridPathCords(16, 3),
)
val blueBase: List<GridPathCords> = listOf(
    GridPathCords(14, 9),
    GridPathCords(14, 10),
    GridPathCords(16, 9),
    GridPathCords(16, 10),
)

val redPath: List<GridPathCords> = listOf(
    GridPathCords(18, 0),
    GridPathCords(18, 1),
    GridPathCords(18, 2),
    GridPathCords(18, 3),
    GridPathCords(18, 4),
    GridPathCords(18, 5),
    GridPathCords(18, 6),
    GridPathCords(17, 6),
    GridPathCords(16, 6),
    GridPathCords(15, 6),
    GridPathCords(14, 6),
    GridPathCords(13, 6),
    GridPathCords(12, 6),//12
    GridPathCords(12, 5),
    GridPathCords(12, 4),
    GridPathCords(12, 3),
    GridPathCords(12, 2),
    GridPathCords(12, 1),
    GridPathCords(12, 0),
    GridPathCords(11, 0),
    GridPathCords(10, 0),
    GridPathCords(9, 0),
    GridPathCords(8, 0),
    GridPathCords(7, 0),
    GridPathCords(6, 0),
    GridPathCords(5, 0),
    GridPathCords(4, 0),
    GridPathCords(3, 0),
    GridPathCords(2, 0),
    GridPathCords(1, 0),
    GridPathCords(0, 0),
    GridPathCords(0, 1),
    GridPathCords(0, 2),
    GridPathCords(0, 3),
    GridPathCords(0, 4),
    GridPathCords(0, 5),
    GridPathCords(0, 6),
    GridPathCords(0, 7),
    GridPathCords(0, 8),
    GridPathCords(0, 9),
    GridPathCords(0, 10),
    GridPathCords(0, 11),
    GridPathCords(0, 12),
    GridPathCords(1, 12),
    GridPathCords(2, 12),
    GridPathCords(3, 12),
    GridPathCords(4, 12),
    GridPathCords(5, 12),
    GridPathCords(6, 12),
    GridPathCords(7, 12),
    GridPathCords(8, 12),
    GridPathCords(9, 12),
    GridPathCords(10, 12),
    GridPathCords(11, 12),
    GridPathCords(12, 12),
    GridPathCords(12, 11),
    GridPathCords(12, 10),
    GridPathCords(12, 9),
    GridPathCords(12, 8),
    GridPathCords(12, 7),//59
    GridPathCords(11, 7),//60
    GridPathCords(11, 6),
    GridPathCords(10, 6),
    GridPathCords(9, 6),
    GridPathCords(8, 6),
    GridPathCords(7, 6),
    GridPathCords(6, 6),
    GridPathCords(6, 5),
    GridPathCords(7, 4),
    GridPathCords(8, 4),
    GridPathCords(9, 3),
    GridPathCords(9, 2),
    GridPathCords(8, 2),
    GridPathCords(7, 2),
    GridPathCords(6, 2),
    GridPathCords(5, 3),
    GridPathCords(4, 4),
    GridPathCords(3, 5),
    GridPathCords(3, 6),
    GridPathCords(2, 6),//79
)
val bluePath: List<GridPathCords> = listOf(
    GridPathCords(18, 12),
    GridPathCords(18, 11),
    GridPathCords(18, 10),
    GridPathCords(18, 9),
    GridPathCords(18, 8),
    GridPathCords(18, 7),
    GridPathCords(18, 6),
    GridPathCords(17, 6),
    GridPathCords(16, 6),
    GridPathCords(15, 6),
    GridPathCords(14, 6),
    GridPathCords(13, 6),
    GridPathCords(12, 6),//12
    GridPathCords(12, 7),
    GridPathCords(12, 8),
    GridPathCords(12, 9),
    GridPathCords(12, 10),
    GridPathCords(12, 11),
    GridPathCords(12, 12),
    GridPathCords(11, 12),
    GridPathCords(10, 12),
    GridPathCords(9, 12),
    GridPathCords(8, 12),
    GridPathCords(7, 12),
    GridPathCords(6, 12),
    GridPathCords(5, 12),
    GridPathCords(4, 12),
    GridPathCords(3, 12),
    GridPathCords(2, 12),
    GridPathCords(1, 12),
    GridPathCords(0, 12),
    GridPathCords(0, 11),
    GridPathCords(0, 10),
    GridPathCords(0, 9),
    GridPathCords(0, 8),
    GridPathCords(0, 7),
    GridPathCords(0, 6),
    GridPathCords(0, 5),
    GridPathCords(0, 4),
    GridPathCords(0, 3),
    GridPathCords(0, 2),
    GridPathCords(0, 1),
    GridPathCords(0, 0),
    GridPathCords(1, 0),
    GridPathCords(2, 0),
    GridPathCords(3, 0),
    GridPathCords(4, 0),
    GridPathCords(5, 0),
    GridPathCords(6, 0),
    GridPathCords(7, 0),
    GridPathCords(8, 0),
    GridPathCords(9, 0),
    GridPathCords(10, 0),
    GridPathCords(11, 0),
    GridPathCords(12, 0),
    GridPathCords(12, 1),
    GridPathCords(12, 2),
    GridPathCords(12, 3),
    GridPathCords(12, 4),
    GridPathCords(12, 5),//59
    GridPathCords(11, 5),
    GridPathCords(11, 6),
    GridPathCords(10, 6),
    GridPathCords(9, 6),
    GridPathCords(8, 6),
    GridPathCords(7, 6),
    GridPathCords(6, 6),
    GridPathCords(6, 7),
    GridPathCords(7, 8),
    GridPathCords(8, 8),
    GridPathCords(9, 9),
    GridPathCords(9, 10),
    GridPathCords(8, 10),
    GridPathCords(7, 10),
    GridPathCords(6, 10),
    GridPathCords(5, 9),
    GridPathCords(4, 8),
    GridPathCords(3, 7),
    GridPathCords(3, 6),
    GridPathCords(2, 6)
)
val pathCords = redPath.union(bluePath)
val safe: List<GridPathCords> = listOf(
    GridPathCords(0, 0),
    GridPathCords(0, 6),
    GridPathCords(0, 12),
    GridPathCords(6, 0),
    GridPathCords(6, 6),
    GridPathCords(6, 12),
    GridPathCords(12, 0),
    GridPathCords(12, 6),
    GridPathCords(12, 12),
    GridPathCords(18, 6),
    GridPathCords(11, 7),
    GridPathCords(11, 5),
)










